require('core.plugin')
require('core.remap')
require('core.setting')
require('core.config.comment')
require('core.config.lsp')
require('core.config.lualine')
require('core.config.nvimtree')
require('core.config.treesitter')
