require 'core.config.autopairs'
require 'core.config.bufferline'
require 'core.config.flutter'
require 'core.config.indent'
require 'core.config.lsp'
require 'core.config.lualine'
require 'core.config.telescope'
require 'core.config.treesitter'
